### ISSUE TITLE
PMSet in Postflight.

### ISSUE THREAD

**Issue by WardsParadox** [jmartinez0837/Munki-Overnight#1]
Just an FYI, the PMSET in the post flight script will overwrite each other. It has to be setup like such:
	sudo pmset repeat wakeorpoweron MTWRF 00:00:00  shutdown MTWRFSU 00:00:00;
Noticed it from my fork so I figured I would let you know.
adjust time per the original. Thanks again for the wonderful script!

**Comment by WardsParadox** [comment]
Ya I was half asleep then. I couldn't remember where the issue was created. Sorry about the absolute waste of time.

**Comment by jmartinez0837** [comment]
no there really was an issue with the pmset. thanks for finding. im looking into your version and thinking of adapting it since its built into munki plist. Nice work

**Comment by WardsParadox** [comment]
I could add you as an editor to the one I'm working on if you like. It seems to be working great in our environment currently, so once again thank you for the amazing script! :+1:
